server.port=8080
spring.datasource.url=jdbc:postgresql://localhost/bookstore
spring.datasource.username=your_db_user
spring.datasource.password=your_db_pass
roles.config.path=Client/src/main/resources/roles.json